sp:
    fastqc/data:
        fn: 'fastqc_data.txt'
    fastqc/zip:
        fn: '*_fastqc.zip'
    fastqc/html:
        fn: '*_fastqc.html'
    fastqc/theoretical_gc:
        fn: '*fastqc_theoretical_gc*'

